# Generated by Django 4.2.13 on 2024-05-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="nome_cliente",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="descricao",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.cliente",
            ),
            preserve_default=False,
        ),
    ]
