# Generated by Django 4.2.13 on 2024-05-16 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0002_cliente_remove_agendamento_nome_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="hora",
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
    ]
