# Generated by Django 4.2.13 on 2024-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0003_agendamento_hora"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="concluido",
            field=models.BooleanField(default=False),
        ),
    ]
